package tiger.common.dal.persistence.icbc;

/**
 * Created by 王硕买个大葱头 on 2017/1/13.
 */
public class Wangshuo_temp {
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wangshuo_temp.name
     *
     * @return the value of wangshuo_temp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wangshuo_temp.name
     *
     * @param name the value for wangshuo_temp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}
